# Environment variables
DD_SOURCE_API_URL = "DD_SOURCE_API_URL"
DD_SOURCE_API_KEY = "DD_SOURCE_API_KEY"
DD_SOURCE_APP_KEY = "DD_SOURCE_APP_KEY"
DD_DESTINATION_API_URL = "DD_DESTINATION_API_URL"
DD_DESTINATION_API_KEY = "DD_DESTINATION_API_KEY"
DD_DESTINATION_APP_KEY = "DD_DESTINATION_APP_KEY"

# Default variables
DEFAULT_API_URL = "https://api.datadoghq.com/"
RESOURCE_OUTPUT_PATH = "/generated/datadog/{}"
DEFAULT_STATE_PATH = "/state/"
DEFAULT_STATE_NAME = "terraform.tfstate.{}"
