# Environment variables
DD_SOURCE_API_URL = "DD_SOURCE_API_URL"
DD_SOURCE_API_KEY = "DD_SOURCE_API_KEY"
DD_SOURCE_APP_KEY = "DD_SOURCE_APP_KEY"
DD_DESTINATION_API_URL = "DD_DESTINATION_API_URL"
DD_DESTINATION_API_KEY = "DD_DESTINATION_API_KEY"
DD_DESTINATION_APP_KEY = "DD_DESTINATION_APP_KEY"
DD_HTTP_CLIENT_RETRY_TIMEOUT = "DD_HTTP_CLIENT_RETRY_TIMEOUT"

# Default variables
DEFAULT_API_URL = "https://api.datadoghq.com/"
RESOURCES_DIR = "resources/"
RESOURCE_FILE_PATH = "resources/{}/{}.json"
SOURCE_RESOURCES_DIR = "resources/source"
DESTINATION_RESOURCES_DIR = "resources/destination"

LOGGER_NAME = "datadog_sync_cli"
