name: Datadog Test Optimization

permissions: 
  checks: write
  contents: read

on:
  schedule:
    # every hour, 9-5 eastern, M-F
    - cron: '15 12-21 * * 1-5'

  push:
    branches:
      - 'main'
      - 'michael.richey/dd-test-opt'

env:
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  DD_DESTINATION_API_KEY: ${{ secrets.DD_DESTINATION_API_KEY }}
  DD_DESTINATION_APP_KEY: ${{ secrets.DD_DESTINATION_APP_KEY }}
  DD_DESTINATION_API_URL: ${{ secrets.DD_DESTINATION_API_URL }}
  DD_SOURCE_API_KEY: ${{ secrets.DD_SOURCE_API_KEY }}
  DD_SOURCE_APP_KEY: ${{ secrets.DD_SOURCE_APP_KEY }}
  DD_SOURCE_API_URL: ${{ secrets.DD_SOURCE_API_URL }}
  RECORD: false

jobs:
  test-optimization:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c
        with:
          python-version: 3.12
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install requirements
        run: |
          python -m pip install .
          python -m pip install -r scripts/test_requirements.txt
      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@fa5d4c02a5f2329cf2c62a70fd8ec532317af1c9
        with:
          languages: python
          api_key: ${{env.DD_API_KEY}}
          site: datadoghq.com
      - name: Run tests
        shell: bash
        run: pytest --ddtrace
