name: Datadog Test Optimization

permissions: 
  checks: write
  contents: read

on: push

env:
  DD_API_KEY: ${{ secrets.DD_API_KEY }}

jobs:
  test-optimization:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python -m pip install .
          python -m pip install -r scripts/test_requirements.txt
      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: python
          api_key: ${{env.DD_API_KEY}}
          site: datadoghq.com
        - name: Run tests
          shell: bash
          run: pytest
