name: Datadog Test Optimization

permissions: 
  checks: write
  contents: read

on: push

env:
  DD_API_KEY: ${{ secrets.DD_API_KEY }}

jobs:
  test-optimization:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: python
          api_key: ${{env.DD_API_KEY}}
          site: datadoghq.com
